### ISSUE TITLE
Duration rounded down

### ISSUE THREAD

**Issue by sveinbjornt** [amugofjava/mp3_info#3]
Why is the duration of the MP3 file in seconds rounded down to nearest integer? I wanted to use this package to show the duration of an MP3 file in fractional seconds.

````
  Duration _processDuration(int fileSizeBytes, int bitRate) {
    final fileSizeBits = fileSizeBytes * 8;
    final bitRateBits = bitRate * 1000;

    final seconds = fileSizeBits / bitRateBits;

    return Duration(seconds: seconds.floor());
  }
````

**Comment by amugofjava** [comment]
Hi @sveinbjornt,

The original requirement for this library was to support the podcast player I build which only needs the duration to the nearest second. Taking a look at the code now, I can see that was unnecessary and I am happy to update the code to the millisecond level or accept a PR if you wished to do that. Thanks for bringing this to my attention.

**Comment by sveinbjornt** [comment]
Thank you for your prompt reply! I'll submit a PR.

**Comment by sveinbjornt** [comment]
PR: https://github.com/amugofjava/mp3_info/pull/4

By the way, thank you for making and sharing this small (but useful) library.

**Comment by amugofjava** [comment]
Thanks for the PR. I've pushed v0.2.1 to pub.dev.
